### ISSUE TITLE
raw message in publish?

### ISSUE THREAD

**Issue by mmjames** [maxnachlinger/log4js-node-amqp#1]
we have a very specific format via the layout pattern that is being parsed for use in elastic search.  this is broken by the way the publish function adds it's own custom json format.  I am curious if you think it would be useful to allow an option to just publish the raw message through to the exchange?  For example the below works for our use case since most of this additional data is contained in the layout pattern.

<pre><code>
while (logEventBuffer.length > 0) {
			toLog = logEventBuffer.shift();
			_exchange.publish(
				_options.publish.routingKey,
				setObjectDefaults(
					toLog.data
					, _options.additionalInfo),
				_options.publish
			);
		}
</code></pre>

Thanks,
   Matt

**Comment by maxnachlinger** [comment]
Hey Matt. That's an interesting idea! I could see adding an option to simply publish the raw message to the exchange, but would you still expect to have the keys in ``_options.additionalInfo`` present in that message? Sounds like your message is a string, so I could also see not using the keys in ``_options.additionalInfo`` for that case. What do you think?

**Comment by maxnachlinger** [comment]
Actually, how about an option to provide a function transforming the log-event before it's sent to the exchange? This wouldn't hurt current users of this library, as the default implementation of that option would be what's currently used now.

**Comment by mmjames** [comment]
Nice! I like that idea.  How would you like to proceed? ( and yes, you are correct, I don't need the additionalInfo either, just the raw message to be published).

**Comment by maxnachlinger** [comment]
Let's give it a try; I'll implement this tonight in a branch and you guys can see if it works out.

**Comment by mmjames** [comment]
Sounds like a plan.  Thank you for the support!

**Comment by maxnachlinger** [comment]
Actually the change was trivial, please give the branch a try:
``npm i maxnachlinger/log4js-node-amqp#interceptor --save``

**Comment by mmjames** [comment]
great, thanks for the quick turnaround! I'm guessing this isn't going to work if my appender is defined in a .json file?

**Comment by maxnachlinger** [comment]
Right, JSON is obviously a format for data-exchange etc so functions in JSON wouldn't work :) Of course I've no idea what your specific use case is, but for my part, I've stopped doing configs in JSON simply because it makes things like providing defaults or overrides for missing env vars etc difficult.  Let me know if this doesn't work out and we can think of another solution.

**Comment by mmjames** [comment]
I totally meant  to put a smiley on that last message.  I moved my appender setup to the proper place in my config and it works like a charm.  Thanks again!!!

**Comment by maxnachlinger** [comment]
OK solid, I'll merge that branch in and kick it to npm.
