### ISSUE TITLE
Appender causing hang in gulp script

### ISSUE THREAD

**Issue by jjmartin** [maxnachlinger/log4js-node-amqp#3]
i'm trying to add some logging to my gulp script...  when I add this as an appender, the gulp script hangs and never finishes until i hit ctrl-c.   WHen i just add log4js with just the console, it doesn't hang.

Do i need to do something to close out the stuff the appender is doing?

**Comment by maxnachlinger** [comment]
Hey Jeff,

It sounds like the connection to RabbitMQ isn't being closed, would you mind adding a breakpoint or a console.log to https://github.com/maxnachlinger/log4js-node-amqp/blob/b2c2b3005f956f8544aa541bbb069f1200ca7378/lib/index.js#L49 and seeing if the ``exit`` event handler runs?

**Comment by jjmartin** [comment]
ok thanks for fast answer - after looking at your code, we saw that you are doing that exit.  the issue was that gulp doesn't call exit itself... so you can add that :
```gulp.doneCallback = function (){
    process.exit();
}```

**Comment by maxnachlinger** [comment]
Actually, it seems as if log4js allows appenders to expose a ``shutdown()`` method for just this case (see: https://github.com/nomiddlename/log4js-node/blob/515291b1dbfbc0da29de86fc5908b71f97d88a4f/lib/log4js.js#L433). I'll add that method to this appender and bump the version.

**Comment by maxnachlinger** [comment]
Hey Jeff,
I've added support for ``shutdown()`` in ``1.0.1``, that version also no longer creates and binds ``logQ`` to the exchange by default. If you're up for it, give that version a shot.
