### ISSUE TITLE
Auto creating queue and binding routing key

### ISSUE THREAD

**Issue by mmjames** [maxnachlinger/log4js-node-amqp#4]
Hey Max,
  We just noticed this and were wondering if there was a way around it with the current implementation.  

It looks like the logQ is auto creating and binding our routing key to it when we publish.  What we really want it to simply publish to the exchange.  We have custom queues that will be routed to from the exchange where the messages are parsed by log stash and put into elastic search.

Thank you!

**Comment by maxnachlinger** [comment]
Thanks for opening that issue. I'm happy to report that I've a first pass at a fix. Now to avoid ``logQ`` being auto-created and bound you simply omit the ``options.queue`` key (if you've already omitted it, then you're fine). Would you mind installing the ``issue4`` branch and giving it a test? You can do that via:
```shell
npm i maxnachlinger/log4js-node-amqp#issue4
```

**Comment by mmjames** [comment]
Thank you for the prompt action on this issue Max.  I have downloaded and applied your fix to our application and was able to verify it no longer creates a queue and we still get messages through our exchange.  Do let me know when it's deployed to npm as an official release.

**Comment by maxnachlinger** [comment]
Deployed as ``version 1.0.0``. Please ``npm i log4js-node-amqp`` and let me know if things break. - No really, it'll be fine, honest :)
