### ISSUE TITLE
log4js-node-amqp version out of date in example

### ISSUE THREAD

**Issue by wayne-nlt** [maxnachlinger/log4js-node-amqp#8]
The version of the log4js-node-amqp dependency in the package.json file [here](https://github.com/maxnachlinger/log4js-node-amqp/blob/master/example/log/package.json#L5) is out of date.

I could send a PR that updates the version, but I'm not sure what the best way to handle it going forward is, it seems that you can't reference a relative directory from the package.json file.

**Comment by maxnachlinger** [comment]
@wayne-nlt I somehow missed this issue - and feel pretty silly right about now :( I'll update these dependencies and push up a new version.
